modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/mrbysco/dense-trees/issues"
license="MIT"

[[mods]]
modId="densetrees"
version="${file.jarVersion}"
displayName="Dense Trees"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dense-trees"
authors="Mrbysco"
description='''
Adds dense versions of vanilla trees that craft into 64 planks instead of 4.
'''
credits="TelephaticGrunt for the idea"
[[dependencies.densetrees]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.densetrees]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"