modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/mrbysco/dense-trees/issues"
license="MIT"

[[mods]]
modId="densetrees"
version="${file.jarVersion}"
displayName="Dense Trees"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dense-trees"
authors="Mrbysco"
description='''
Adds dense versions of vanilla trees that craft into 64 planks instead of 4.
'''
credits="TelephaticGrunt for the idea"
[[dependencies.densetrees]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"