package com.mrbysco.densetrees.world;

import com.mrbysco.densetrees.DenseTrees;
import net.minecraft.core.Registry;
import net.minecraft.data.worldgen.placement.PlacementUtils;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.WeightedPlacedFeature;
import net.minecraft.world.level.levelgen.feature.configurations.RandomFeatureConfiguration;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

import java.util.List;

public class DenseVegetationFeatures {
	public static final DeferredRegister<ConfiguredFeature<?, ?>> CONFIGURED_FEATURES = DeferredRegister.create(Registry.CONFIGURED_FEATURE_REGISTRY, DenseTrees.MOD_ID);

	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_FLOWER_FOREST = CONFIGURED_FEATURES.register("dense_trees_flower_forest", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_BIRCH_BEES_002.getHolder().orElseThrow(), 0.2F), new WeightedPlacedFeature(DenseTreePlacements.DENSE_FANCY_OAK_BEES_002.getHolder().orElseThrow(), 0.1F)), DenseTreePlacements.DENSE_OAK_BEES_002.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_MEADOW_TREES = CONFIGURED_FEATURES.register("dense_meadow_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_FANCY_OAK_BEES.getHolder().orElseThrow(), 0.5F)), DenseTreePlacements.DENSE_SUPER_BIRCH_BEES.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_TAIGA = CONFIGURED_FEATURES.register("dense_trees_taiga", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_PINE_CHECKED.getHolder().orElseThrow(), 0.33333334F)), DenseTreePlacements.DENSE_SPRUCE_CHECKED.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_GROVE = CONFIGURED_FEATURES.register("dense_trees_grove", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_PINE_ON_SNOW.getHolder().orElseThrow(), 0.33333334F)), DenseTreePlacements.DENSE_SPRUCE_ON_SNOW.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_SAVANNA = CONFIGURED_FEATURES.register("dense_trees_savanna", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_ACACIA_CHECKED.getHolder().orElseThrow(), 0.8F)), DenseTreePlacements.DENSE_OAK_CHECKED.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_BIRCH_TALL = CONFIGURED_FEATURES.register("dense_birch_tall", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_SUPER_BIRCH_BEES_0002.getHolder().orElseThrow(), 0.5F)), DenseTreePlacements.DENSE_BIRCH_BEES_0002_PLACED.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_WINDSWEPT_HILLS = CONFIGURED_FEATURES.register("dense_trees_windswept_hills", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_SPRUCE_CHECKED.getHolder().orElseThrow(), 0.666F), new WeightedPlacedFeature(DenseTreePlacements.DENSE_FANCY_OAK_CHECKED.getHolder().orElseThrow(), 0.1F)), DenseTreePlacements.DENSE_OAK_CHECKED.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_WATER = CONFIGURED_FEATURES.register("dense_trees_water", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_FANCY_OAK_CHECKED.getHolder().orElseThrow(), 0.1F)), DenseTreePlacements.DENSE_OAK_CHECKED.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_BIRCH_AND_OAK = CONFIGURED_FEATURES.register("dense_trees_birch_and_oak", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_BIRCH_BEES_0002_PLACED.getHolder().orElseThrow(), 0.2F), new WeightedPlacedFeature(DenseTreePlacements.DENSE_FANCY_OAK_BEES_0002.getHolder().orElseThrow(), 0.1F)), DenseTreePlacements.DENSE_OAK_BEES_0002.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_PLAINS = CONFIGURED_FEATURES.register("dense_trees_plains", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PlacementUtils.inlinePlaced(DenseTreeFeatures.DENSE_FANCY_OAK_BEES_005.getHolder().orElseThrow()), 0.33333334F)), PlacementUtils.inlinePlaced(DenseTreeFeatures.DENSE_OAK_BEES_005.getHolder().orElseThrow()))));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_SPARSE_JUNGLE = CONFIGURED_FEATURES.register("dense_trees_sparse_jungle", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_FANCY_OAK_CHECKED.getHolder().orElseThrow(), 0.1F), new WeightedPlacedFeature(DenseTreePlacements.DENSE_JUNGLE_BUSH.getHolder().orElseThrow(), 0.5F)), DenseTreePlacements.DENSE_JUNGLE_TREE_CHECKED.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_OLD_GROWTH_SPRUCE_TAIGA = CONFIGURED_FEATURES.register("dense_trees_old_growth_spruce_taiga", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_MEGA_SPRUCE_CHECKED.getHolder().orElseThrow(), 0.33333334F), new WeightedPlacedFeature(DenseTreePlacements.DENSE_PINE_CHECKED.getHolder().orElseThrow(), 0.33333334F)), DenseTreePlacements.DENSE_SPRUCE_CHECKED.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_OLD_GROWTH_PINE_TAIGA = CONFIGURED_FEATURES.register("dense_trees_old_growth_pine_taiga", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_MEGA_SPRUCE_CHECKED.getHolder().orElseThrow(), 0.025641026F), new WeightedPlacedFeature(DenseTreePlacements.DENSE_MEGA_PINE_CHECKED.getHolder().orElseThrow(), 0.30769232F), new WeightedPlacedFeature(DenseTreePlacements.DENSE_PINE_CHECKED.getHolder().orElseThrow(), 0.33333334F)), DenseTreePlacements.DENSE_SPRUCE_CHECKED.getHolder().orElseThrow())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DENSE_TREES_JUNGLE = CONFIGURED_FEATURES.register("dense_trees_jungle", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(DenseTreePlacements.DENSE_FANCY_OAK_CHECKED.getHolder().orElseThrow(), 0.1F), new WeightedPlacedFeature(DenseTreePlacements.DENSE_JUNGLE_BUSH.getHolder().orElseThrow(), 0.5F), new WeightedPlacedFeature(DenseTreePlacements.DENSE_MEGA_JUNGLE_TREE_CHECKED.getHolder().orElseThrow(), 0.33333334F)), DenseTreePlacements.DENSE_JUNGLE_TREE_CHECKED.getHolder().orElseThrow())));

}
